name: "🐛 Bug Report"
description: "Report an issue with the project"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## 🐞 Describe the Bug\nA clear and concise description of what the bug is."

  - type: textarea
    id: bug-description
    attributes:
      label: "What happened?"
      description: "Provide details about the issue"
      placeholder: "Explain the bug here..."
      value: "Steps to reproduce:\n1. ...\n2. ...\n3. ..."

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "What should have happened?"
      placeholder: "Describe what you expected to happen."
      value: "Expected result: ..."

  - type: input
    id: system-info
    attributes:
      label: "System Information"
      description: "Provide details about your system (OS, Browser, etc.)."
      placeholder: "OS: Windows 11, Browser: Chrome 120"
``

