name: "🐛 Bug Report"
description: "Report an issue with the project"
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Describe the Bug
        A clear and concise description of what the bug is.

  - type: textarea
    id: bug-description
    attributes:
      label: "What happened?"
      description: "Provide details about the issue"
      placeholder: "Explain the bug here..."

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "Describe what you expected to happen."

  - type: input
    id: system-info
    attributes:
      label: "System Information"
      description: "Provide details about your system (OS, Browser, etc.)."
      placeholder: "OS: Arch Linux, Browser: Zen"
