name: "✨ Feature Suggestion"
description: "Suggest a new feature for the project"
title: "[FEATURE] Short title of the feature"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Proposal  
        Provide a detailed description of the feature.

  - type: textarea
    id: feature-proposal
    attributes:
      label: "Feature Proposal"
      description: "What is the feature about?"
      placeholder: "Describe the feature here..."
      
  - type: textarea
    id: implementation
    attributes:
      label: "Possible Implementation"
      description: "How can this be implemented? Mention technologies or approaches."
      placeholder: "Describe the implementation details here..."
      
  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "Why is this feature needed? How does it benefit users?"
      placeholder: "Explain the use case here..."
      
  - type: textarea
    id: visual-references
    attributes:
      label: "Visual References (if applicable)"
      description: "Attach screenshots, links, or other references."
      placeholder: "Paste links or image references here..."
